services:
  app:
    image: gaohaha445/weread-challenge:latest
    pull_policy: always
    environment:
      - WEREAD_DURATION=68
      - WEREAD_HEADLESS=true
      - DEFAULT_BOOK_URL=https://weread.qq.com/web/reader/276323e0813ab90a5g0144d7
      # 如果不想固定阅读链接，删除 DEFAULT_BOOK_URL 后改用：
      # - WEREAD_KEYWORDS=三体,明朝
    volumes:
      - ./.weread:/app/.weread
    shm_size: 2gb
    dns:
      - 223.5.5.5
